#!/bin/bash
# generated by MuG VRE
cd /orozco/services/Rdata/MuG/MuG_userdata//MuGUSER57ecf22d91df3/.tmp

# Running PyDock tool ...

echo '# Start time:' $(date) > /orozco/services/Rdata/MuG/MuG_userdata//MuGUSER57ecf22d91df3/demo/demo.log
/home/user/bin/mug/docking_dna.py  --receptor '/orozco/services/Rdata/MuG/MuG_userdata//MuGUSER57ecf22d91df3/uploads/1HCG.pdb' --ligand '/orozco/services/Rdata/MuG/MuG_userdata//MuGUSER57ecf22d91df3/uploads/1NSD.pdb' --models 1 --scoring PyDockDNA --project demo --abs_path /orozco/services/Rdata/MuG/MuG_userdata/ --user_id MuGUSER57ecf22d91df3 >> /orozco/services/Rdata/MuG/MuG_userdata//MuGUSER57ecf22d91df3/demo/demo.log 2>&1
echo '# End time:' $(date) >> /orozco/services/Rdata/MuG/MuG_userdata//MuGUSER57ecf22d91df3/demo/demo.log
